/*
 * HlavneOkno.java
 *
 * Created on 31 July 2008, 00:27
 */

package manola;

import com.db4o.ObjectSet;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author  simo
 */
public class HlavneOkno extends javax.swing.JFrame {
    
    Databaza db = new Databaza();
    /** Creates new form HlavneOkno */
    public HlavneOkno() {
        initComponents();
        
        tbl_zakaznik.setAutoCreateRowSorter(true);
        tbl_zmluvy.setAutoCreateRowSorter(true);
        
        //nastavenia mien zaloziek
        tabPanel.setTitleAt(0,"Zakaznici");
        tabPanel.setTitleAt(1,"Zmluvy");
        tabPanel.setTitleAt(2,"Nastavenia");
        
        
        //tbl_zmluvy.setAutoCreateRowSorter(true);
        
        nacitajUdajeZakaznik();
        nacitajUdajeZmluva();
        nacitajNastavenia();
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jtf_filter_zakaznik = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_zakaznik = new javax.swing.JTable();
        btn_zakaznik_detail = new javax.swing.JButton();
        btn_pridaj_zmluvu = new javax.swing.JButton();
        btn_pridaj_zakaznika = new javax.swing.JButton();
        btn_obnov_zakaznika = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_obnov_zmluvy = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_zmluvy = new javax.swing.JTable();
        btn_detail_zmluva = new javax.swing.JButton();
        jtf_filter_zmluva = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jsp_urok1 = new javax.swing.JSpinner();
        jsp_urok2 = new javax.swing.JSpinner();
        jsp_urok3 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jsp_urok4 = new javax.swing.JSpinner();
        jsp_urok5 = new javax.swing.JSpinner();
        jsp_id_zmluvy = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_uloz_zmeny_nastavenia = new javax.swing.JButton();
        btn_zrus_zmeny_nastavenia = new javax.swing.JButton();
        jtb_edituj_nastavenia = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manola 2008 (20090102)");
        setBackground(new java.awt.Color(255, 153, 0));
        setForeground(new java.awt.Color(255, 153, 0));

        jtf_filter_zakaznik.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtf_filter_zakaznikCaretUpdate(evt);
            }
        });

        tbl_zakaznik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cislo OP", "Meno", "Adresa", "Stav"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_zakaznik);

        jScrollPane1.setViewportView(jScrollPane2);

        btn_zakaznik_detail.setText("Detail");
        btn_zakaznik_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zakaznik_detailActionPerformed(evt);
            }
        });

        btn_pridaj_zmluvu.setText("Pridaj zmluvu");
        btn_pridaj_zmluvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pridaj_zmluvuActionPerformed(evt);
            }
        });

        btn_pridaj_zakaznika.setText("Pridaj zakaznika");
        btn_pridaj_zakaznika.setToolTipText("Vytvori noveho zakaznika");
        btn_pridaj_zakaznika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pridaj_zakaznikaActionPerformed(evt);
            }
        });

        btn_obnov_zakaznika.setText("Obnov");
        btn_obnov_zakaznika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_obnov_zakaznikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jtf_filter_zakaznik, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(btn_pridaj_zakaznika)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_pridaj_zmluvu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_obnov_zakaznika, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_zakaznik_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_zakaznik_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pridaj_zakaznika)
                    .addComponent(btn_pridaj_zmluvu)
                    .addComponent(btn_obnov_zakaznika)
                    .addComponent(jtf_filter_zakaznik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanel.addTab("tab1", jPanel1);

        btn_obnov_zmluvy.setText("Obnov");
        btn_obnov_zmluvy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_obnov_zmluvyActionPerformed(evt);
            }
        });

        tbl_zmluvy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_zmluvy);

        btn_detail_zmluva.setText("Detail");
        btn_detail_zmluva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detail_zmluvaActionPerformed(evt);
            }
        });

        jtf_filter_zmluva.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtf_filter_zmluvaCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtf_filter_zmluva, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(368, 368, 368)
                        .addComponent(btn_obnov_zmluvy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_detail_zmluva))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_detail_zmluva)
                    .addComponent(btn_obnov_zmluvy)
                    .addComponent(jtf_filter_zmluva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabPanel.addTab("tab2", jPanel2);

        jLabel1.setText("1. tyzden");

        jLabel2.setText("2. tyzden");

        jLabel3.setText("3. tyzden");

        jsp_urok1.setEnabled(false);

        jsp_urok2.setEnabled(false);

        jsp_urok3.setEnabled(false);

        jLabel4.setText("4. tyzden");

        jLabel5.setText("5. tyzden");

        jsp_urok4.setEnabled(false);

        jsp_urok5.setEnabled(false);

        jsp_id_zmluvy.setEnabled(false);

        jLabel6.setText("ID nasledujucej zmluvy");

        jLabel7.setText("Uroky v %");

        btn_uloz_zmeny_nastavenia.setText("Uloz zmeny");
        btn_uloz_zmeny_nastavenia.setToolTipText("Ulozi zmeny vykonane v nastaveniach.");
        btn_uloz_zmeny_nastavenia.setEnabled(false);
        btn_uloz_zmeny_nastavenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uloz_zmeny_nastaveniaActionPerformed(evt);
            }
        });

        btn_zrus_zmeny_nastavenia.setText("Zrus zmeny");
        btn_zrus_zmeny_nastavenia.setToolTipText("Zrusi zmeny vykonane v nastaveniach.");
        btn_zrus_zmeny_nastavenia.setEnabled(false);
        btn_zrus_zmeny_nastavenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zrus_zmeny_nastaveniaActionPerformed(evt);
            }
        });

        jtb_edituj_nastavenia.setText("Edituj nastavenia");
        jtb_edituj_nastavenia.setToolTipText("Umozni menit nastavenia programu.");
        jtb_edituj_nastavenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_edituj_nastaveniaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jsp_urok4))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jsp_urok3))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jsp_urok2))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jsp_urok1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jsp_urok5))))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jsp_id_zmluvy)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtb_edituj_nastavenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_uloz_zmeny_nastavenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_zrus_zmeny_nastavenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsp_id_zmluvy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jsp_urok1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jsp_urok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jsp_urok3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jsp_urok4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jsp_urok5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jtb_edituj_nastavenia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_uloz_zmeny_nastavenia)
                        .addGap(14, 14, 14)
                        .addComponent(btn_zrus_zmeny_nastavenia)))
                .addContainerGap(199, Short.MAX_VALUE))
        );

        tabPanel.addTab("tab3", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-729)/2, (screenSize.height-522)/2, 729, 522);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_filter_zmluvaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtf_filter_zmluvaCaretUpdate
            // TODO add your handling code here:
        filtrujZmluva();
    }//GEN-LAST:event_jtf_filter_zmluvaCaretUpdate

    private void jtf_filter_zakaznikCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtf_filter_zakaznikCaretUpdate
        // TODO add your handling code here:
        filtrujZakaznika();
    }//GEN-LAST:event_jtf_filter_zakaznikCaretUpdate

    private void jtb_edituj_nastaveniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_edituj_nastaveniaActionPerformed
        
        nacitajNastavenia();
        
        ButtonModel btnmdl = jtb_edituj_nastavenia.getModel();
        
        if(btnmdl.isSelected()){
            btn_zrus_zmeny_nastavenia.setEnabled(true);
            btn_uloz_zmeny_nastavenia.setEnabled(true);
            
            jsp_urok1.setEnabled(true);
            jsp_urok2.setEnabled(true);
            jsp_urok3.setEnabled(true);
            jsp_urok4.setEnabled(true);
            jsp_urok5.setEnabled(true);
            
            jsp_id_zmluvy.setEnabled(true);
        }
        else{
            btn_zrus_zmeny_nastavenia.setEnabled(false);
            btn_uloz_zmeny_nastavenia.setEnabled(false);
            
            jsp_urok1.setEnabled(false);
            jsp_urok2.setEnabled(false);
            jsp_urok3.setEnabled(false);
            jsp_urok4.setEnabled(false);
            jsp_urok5.setEnabled(false);
            
            jsp_id_zmluvy.setEnabled(false);
        }

    }//GEN-LAST:event_jtb_edituj_nastaveniaActionPerformed

    private void btn_uloz_zmeny_nastaveniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uloz_zmeny_nastaveniaActionPerformed
        Databaza db = new Databaza();
        
        int u1 = ((SpinnerNumberModel)jsp_urok1.getModel()).getNumber().intValue();
        int u2 = ((SpinnerNumberModel)jsp_urok2.getModel()).getNumber().intValue();
        int u3 = ((SpinnerNumberModel)jsp_urok3.getModel()).getNumber().intValue();
        int u4 = ((SpinnerNumberModel)jsp_urok4.getModel()).getNumber().intValue();
        int u5 = ((SpinnerNumberModel)jsp_urok5.getModel()).getNumber().intValue();
        
        int id = ((SpinnerNumberModel)jsp_id_zmluvy.getModel()).getNumber().intValue();
        
        System.out.println(u1+" "+u2+" "+u3+" "+u4+" "+u5+" "+id);
        db.zmenNastavenia(u1, u2, u3, u4, u5, id);
    }//GEN-LAST:event_btn_uloz_zmeny_nastaveniaActionPerformed

    private void btn_zrus_zmeny_nastaveniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zrus_zmeny_nastaveniaActionPerformed
        nacitajNastavenia();      
    }//GEN-LAST:event_btn_zrus_zmeny_nastaveniaActionPerformed

    private void btn_detail_zmluvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detail_zmluvaActionPerformed
        if(tbl_zmluvy.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Vyber zaznam v tabulke zmluv", "Chyba",0);
        }
        else{
            ZmluvaDetail zmluvaDetail = new ZmluvaDetail(tbl_zmluvy.getValueAt(tbl_zmluvy.getSelectedRow(),0).toString());
            zmluvaDetail.setVisible(true);
        }
    }//GEN-LAST:event_btn_detail_zmluvaActionPerformed

    private void btn_pridaj_zmluvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pridaj_zmluvuActionPerformed
        
        if(tbl_zakaznik.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Vyber zaznam v tabulke zakaznikov", "Chyba",0);
        }
        else{
            int riadok = tbl_zakaznik.getSelectedRow();
        
            String cislo_OP = tbl_zakaznik.getValueAt(riadok, 0).toString();

            NovaZmluva novaZmluva = new NovaZmluva(db.vratPouzivatelaPodlaCislaOP(cislo_OP));
            novaZmluva.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_pridaj_zmluvuActionPerformed

    private void btn_obnov_zmluvyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_obnov_zmluvyActionPerformed
        nacitajUdajeZmluva();
    }//GEN-LAST:event_btn_obnov_zmluvyActionPerformed

    private void btn_obnov_zakaznikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_obnov_zakaznikaActionPerformed
        nacitajUdajeZakaznik();
    }//GEN-LAST:event_btn_obnov_zakaznikaActionPerformed
    
    //zobrazi inforamacie o zakaznikovy
    private void btn_zakaznik_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zakaznik_detailActionPerformed
        
        if(tbl_zakaznik.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Vyber zaznam v tabulke zakaznikov", "Chyba",0);
        }
        else{
            int riadok = tbl_zakaznik.getSelectedRow();

            String cislo_OP = tbl_zakaznik.getValueAt(riadok, 0).toString();


            ZakaznikDetail zakaznikDetail = new ZakaznikDetail(db.vratPouzivatelaPodlaCislaOP(cislo_OP));
            zakaznikDetail.setVisible(true);    
        }
    }//GEN-LAST:event_btn_zakaznik_detailActionPerformed

    private void btn_pridaj_zakaznikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pridaj_zakaznikaActionPerformed
        NovyPouzivatel novyPouzivatel = new NovyPouzivatel();
        novyPouzivatel.setVisible(true);
    }//GEN-LAST:event_btn_pridaj_zakaznikaActionPerformed
    
    
    /**
     *nacita a zobrazi informacie do tabuliek
     *
     **/
    private void nacitajUdajeZakaznik(){
       DefaultTableModel mdl = new DefaultTableModel();
       
       tbl_zakaznik.setModel(mdl);
       
       while(tbl_zakaznik.getRowCount() > 0){
            mdl.removeRow(0);
       }
       
       mdl.addColumn("Rodne cislo");
       mdl.addColumn("Cislo OP");
       mdl.addColumn("Meno");
       mdl.addColumn("Adresa");
      
       
       Databaza db = new Databaza();
       
       Object[] zakaznici = db.vratPouzivatelov();
             
       for (int i = 0; i < zakaznici.length; i++) {
           Pouzivatel novy = (Pouzivatel)zakaznici[i];
           mdl.addRow(new Object[] {novy.cislo_OP.toString(), novy.doplnk_info.toString(), novy.meno.toString()+" "+novy.priezvisko.toString(), novy.adresa.toString()});
       }
    }   
    
    /**
     *Nacita udaje o zmluvach
     **/
    private void nacitajUdajeZmluva(){
       DefaultTableModel mdl = new DefaultTableModel();
       
       tbl_zmluvy.setModel(mdl);
       
       while(tbl_zmluvy.getRowCount() > 0){
            mdl.removeRow(0);
       }
       
       mdl.addColumn("ID");
       mdl.addColumn("Zakaznik");
       mdl.addColumn("Predmet");
       mdl.addColumn("Suma");
       mdl.addColumn("Stav");
       mdl.addColumn("Poznamka");
       
       Databaza db = new Databaza();
       
       Object[] zmluvy = db.vratZmluvy();
           
       for (int i = 0; i < zmluvy.length; i++) {
           Zmluva nova = (Zmluva)zmluvy[i];
           if(nova.datum.getYear() == 2008){
               mdl.addRow(new Object[] {nova.ID.toString(), nova.zakaznik_OP.toString(), nova.predmet.toString(), nova.hodnota+" SK ", nova.stav.toString(), nova.poznamka.toString()});              
           }
           else{
               mdl.addRow(new Object[] {nova.ID.toString(), nova.zakaznik_OP.toString(), nova.predmet.toString(), nova.hodnota+" € ", nova.stav.toString(), nova.poznamka.toString()});
           }
           
       }
    }
    
    /**
     * Nacita nastavenie z databazy
     */
    private void nacitajNastavenia(){
        
        Databaza db = new Databaza();
        
        Nastavenia nastavenia = db.vratNastavenia();
        
        //nacitania udajov o jednotlivych urokoch
        SpinnerNumberModel mdl_urok1 = new SpinnerNumberModel(nastavenia.urok1, 0, 100, 1);
        jsp_urok1.setModel(mdl_urok1);
        
        SpinnerNumberModel mdl_urok2 = new SpinnerNumberModel(nastavenia.urok2, 0, 100, 1);
        jsp_urok2.setModel(mdl_urok2);

        SpinnerNumberModel mdl_urok3 = new SpinnerNumberModel(nastavenia.urok3, 0, 100, 1);
        jsp_urok3.setModel(mdl_urok3);

        SpinnerNumberModel mdl_urok4 = new SpinnerNumberModel(nastavenia.urok4, 0, 100, 1);
        jsp_urok4.setModel(mdl_urok4);

        SpinnerNumberModel mdl_urok5 = new SpinnerNumberModel(nastavenia.urok5, 0, 100, 1);
        jsp_urok5.setModel(mdl_urok5);
        
        //nacitanie is zmluvy
        
        SpinnerNumberModel mdl_id = new SpinnerNumberModel(nastavenia.ID_zmluvy, nastavenia.ID_zmluvy, null, 1);
        jsp_id_zmluvy.setModel(mdl_id);

    }
    
    
    //filtruje udaje v tabulke zakaznikov
    private void filtrujZakaznika(){
        
        TableRowSorter filter_zakaznik = new TableRowSorter(tbl_zakaznik.getModel());
        
        tbl_zakaznik.setRowSorter(filter_zakaznik);
        
        RowFilter  rf = null;
        
        try {
             rf = RowFilter.regexFilter(jtf_filter_zakaznik.getText());
             }
        catch (java.util.regex.PatternSyntaxException e) {
            return;
             }
        filter_zakaznik.setRowFilter(rf);
    }
    
    
        //filtruje udaje v tabulke zakaznikov
    private void filtrujZmluva(){
        
        TableRowSorter filter_zmluva = new TableRowSorter(tbl_zmluvy.getModel());
        
        tbl_zmluvy.setRowSorter(filter_zmluva);
        
        RowFilter  rf = null;
        
        try {
             rf = RowFilter.regexFilter(jtf_filter_zmluva.getText());
             }
        catch (java.util.regex.PatternSyntaxException e) {
            return;
             }
        filter_zmluva.setRowFilter(rf);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HlavneOkno().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_detail_zmluva;
    private javax.swing.JButton btn_obnov_zakaznika;
    private javax.swing.JButton btn_obnov_zmluvy;
    private javax.swing.JButton btn_pridaj_zakaznika;
    private javax.swing.JButton btn_pridaj_zmluvu;
    private javax.swing.JButton btn_uloz_zmeny_nastavenia;
    private javax.swing.JButton btn_zakaznik_detail;
    private javax.swing.JButton btn_zrus_zmeny_nastavenia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jsp_id_zmluvy;
    private javax.swing.JSpinner jsp_urok1;
    private javax.swing.JSpinner jsp_urok2;
    private javax.swing.JSpinner jsp_urok3;
    private javax.swing.JSpinner jsp_urok4;
    private javax.swing.JSpinner jsp_urok5;
    private javax.swing.JToggleButton jtb_edituj_nastavenia;
    private javax.swing.JTextField jtf_filter_zakaznik;
    private javax.swing.JTextField jtf_filter_zmluva;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTable tbl_zakaznik;
    private javax.swing.JTable tbl_zmluvy;
    // End of variables declaration//GEN-END:variables
    
}
