/*
 * NovaZmluva.java
 *
 * Created on 31 July 2008, 01:39
 */

package manola;

import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author  simo
 */
public class NovaZmluva extends javax.swing.JFrame {
    
    private Pouzivatel zakaznik;
    private Calendar kalendar = Calendar.getInstance();
    
    /** Creates new form NovaZmluva */
    public NovaZmluva() {
        initComponents();
    }
    
    
    public NovaZmluva(Pouzivatel novy_zakaznik) {
        initComponents();
             
        
        Databaza db = new Databaza();
        
        int id = db.vratIdZmluvy();
        zakaznik = novy_zakaznik;
        
        lbl_zakaznik.setText(zakaznik.meno+" "+zakaznik.priezvisko);
        lbl_cislo_OP.setText(zakaznik.cislo_OP.toString());
        Calendar cal = Calendar.getInstance();
        
        lbl_ID.setText("M"+cal.get(Calendar.YEAR)+"*");
        
        for (int i = new Integer(id).toString().length(); i < 4; i++) {
            lbl_ID.setText(lbl_ID.getText()+"0");
        }
        
        lbl_ID.setText(lbl_ID.getText()+id);
        
        lbl_datum.setText(kalendar.get(Calendar.DAY_OF_MONTH)+"."+(kalendar.get(Calendar.MONTH)+1)+"."+kalendar.get(Calendar.YEAR));
        }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_ID = new javax.swing.JLabel();
        lbl_zakaznik = new javax.swing.JLabel();
        jtf_predmet = new javax.swing.JTextField();
        jtf_poznamka = new javax.swing.JTextField();
        jtf_hodnota = new javax.swing.JTextField();
        lbl_datum = new javax.swing.JLabel();
        lbl_stav = new javax.swing.JLabel();
        btn_vytvor = new javax.swing.JButton();
        btn_zrus = new javax.swing.JButton();
        lbl_cislo_OP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova zmluva");
        setResizable(false);
        jLabel1.setText("Zakaznik");

        jLabel2.setText("Predmet");

        jLabel3.setText("Poznamka");

        jLabel4.setText("Suma");

        jLabel5.setText("Stav");

        jLabel6.setText("Datum");

        jLabel7.setText("ID zmluvy");

        lbl_ID.setText("lbl_id");

        lbl_zakaznik.setText("jLabel9");

        jtf_predmet.setToolTipText("Predmet zmluvy");
        jtf_predmet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_predmetKeyTyped(evt);
            }
        });

        jtf_poznamka.setToolTipText("Poznamka k zmluve");

        jtf_hodnota.setToolTipText("Suma na ktoru je zmluva uzavreta");
        jtf_hodnota.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtf_hodnotaCaretUpdate(evt);
            }
        });
        jtf_hodnota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_hodnotaKeyTyped(evt);
            }
        });

        lbl_datum.setText("datum");

        lbl_stav.setText("Zalozena");

        btn_vytvor.setText("Vytvor");
        btn_vytvor.setToolTipText("Vytvory zmluvu");
        btn_vytvor.setEnabled(false);
        btn_vytvor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vytvorActionPerformed(evt);
            }
        });

        btn_zrus.setText("Zrus");
        btn_zrus.setToolTipText("Zrusi vytvaranie zmluvy");
        btn_zrus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zrusActionPerformed(evt);
            }
        });

        lbl_cislo_OP.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtf_poznamka, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_hodnota, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbl_zakaznik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_cislo_OP, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_stav, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_datum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_predmet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_vytvor, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addGap(193, 193, 193)
                        .addComponent(btn_zrus, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_zakaznik)
                    .addComponent(lbl_cislo_OP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_ID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_predmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_poznamka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_hodnota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_stav))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_datum))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_zrus)
                    .addComponent(btn_vytvor))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-439)/2, (screenSize.height-267)/2, 439, 267);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_hodnotaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtf_hodnotaCaretUpdate
        try{
            new Float(jtf_hodnota.getText()).floatValue();
        }
        catch (NumberFormatException exc){
            JOptionPane.showMessageDialog(null, jtf_hodnota.getText()+" nie je cislo.", "Nespravny format cisla",0);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jtf_hodnotaCaretUpdate

    private void btn_vytvorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vytvorActionPerformed
        vytvorNovuZmluvu();
        this.dispose();
    }//GEN-LAST:event_btn_vytvorActionPerformed

    private void jtf_hodnotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_hodnotaKeyTyped
        skontrolojUdaje();
       
    }//GEN-LAST:event_jtf_hodnotaKeyTyped

    private void jtf_predmetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_predmetKeyTyped
        skontrolojUdaje();
    }//GEN-LAST:event_jtf_predmetKeyTyped

    private void btn_zrusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zrusActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_zrusActionPerformed
    
    /**
     *Skontroluje ci su vyplenene udaje o predmete zmluvy a sume na ktroru sa uzatvara
     **/
    private void skontrolojUdaje(){
       if(jtf_predmet.getText().toString().length() > 0 && jtf_hodnota.getText().toString().length() > 0) btn_vytvor.setEnabled(true);
       else btn_vytvor.setEnabled(false);
    }
    
    /**
     * Vytvori novu zmluvu
     */
    private void vytvorNovuZmluvu(){
        Zmluva nova = new Zmluva(lbl_cislo_OP.getText().toString(),jtf_predmet.getText().toString(), jtf_poznamka.getText().toString(), new Float(jtf_hodnota.getText().toString()).floatValue());
        
        Databaza db = new Databaza();
        db.pridajZmluvu(nova);
        
        ZmluvaDetail zmluvaDetail = new ZmluvaDetail(lbl_ID.getText());
        zmluvaDetail.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovaZmluva().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_vytvor;
    private javax.swing.JButton btn_zrus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jtf_hodnota;
    private javax.swing.JTextField jtf_poznamka;
    private javax.swing.JTextField jtf_predmet;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_cislo_OP;
    private javax.swing.JLabel lbl_datum;
    private javax.swing.JLabel lbl_stav;
    private javax.swing.JLabel lbl_zakaznik;
    // End of variables declaration//GEN-END:variables
    
}
