/*
 * NovyPouzivatel.java
 *
 * Created on 30 July 2008, 23:40
 */

package manola;

/**
 *
 * @author  simo
 */
public class NovyPouzivatel extends javax.swing.JFrame {
    
    /** Creates new form NovyPouzivatel */
    public NovyPouzivatel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtf_meno = new javax.swing.JTextField();
        jtf_priezvisko = new javax.swing.JTextField();
        jtf_adresa = new javax.swing.JTextField();
        jtf_cislo_OP = new javax.swing.JTextField();
        jcb_pohlavie = new javax.swing.JComboBox();
        jcb_stav = new javax.swing.JComboBox();
        btn_pridaj_zakaznika = new javax.swing.JButton();
        btn_zrus_zakaznika = new javax.swing.JButton();
        Doplnk_info = new javax.swing.JLabel();
        jtf_doplnk_info = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pridanie noveho zakaznika");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setText("Meno");

        jLabel2.setText("Priezvisko");

        jLabel3.setText("Adresa");

        jLabel4.setText("Rodne Cislo:");

        jLabel5.setText("Pohlavie");

        jLabel6.setText("Stav");

        jtf_meno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_menoKeyTyped(evt);
            }
        });

        jtf_priezvisko.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_priezviskoKeyTyped(evt);
            }
        });

        jtf_adresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_adresaKeyTyped(evt);
            }
        });

        jtf_cislo_OP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_cislo_OPKeyTyped(evt);
            }
        });

        jcb_pohlavie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muz", "Zena" }));

        jcb_stav.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Slobodny/a", "Zenaty/Vydata" }));

        btn_pridaj_zakaznika.setText("Pridaj");
        btn_pridaj_zakaznika.setEnabled(false);
        btn_pridaj_zakaznika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pridaj_zakaznikaActionPerformed(evt);
            }
        });

        btn_zrus_zakaznika.setText("Zrus");
        btn_zrus_zakaznika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zrus_zakaznikaActionPerformed(evt);
            }
        });

        Doplnk_info.setText("Cislo OP:");

        jtf_doplnk_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_doplnk_infoActionPerformed(evt);
            }
        });
        jtf_doplnk_info.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_doplnk_infoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_pridaj_zakaznika, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                        .addComponent(btn_zrus_zakaznika, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcb_pohlavie, javax.swing.GroupLayout.Alignment.LEADING, 0, 300, Short.MAX_VALUE)
                            .addComponent(jcb_stav, javax.swing.GroupLayout.Alignment.LEADING, 0, 300, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(Doplnk_info))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_cislo_OP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(jtf_priezvisko, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(jtf_meno, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(jtf_adresa, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(jtf_doplnk_info, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtf_meno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtf_priezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_adresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_cislo_OP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Doplnk_info)
                    .addComponent(jtf_doplnk_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcb_pohlavie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcb_stav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_zrus_zakaznika)
                    .addComponent(btn_pridaj_zakaznika))
                .addGap(22, 22, 22))
        );
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-406)/2, (screenSize.height-346)/2, 406, 346);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_doplnk_infoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_doplnk_infoKeyTyped
        skontrolujUdaje();
    }//GEN-LAST:event_jtf_doplnk_infoKeyTyped

    private void jtf_doplnk_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_doplnk_infoActionPerformed
        skontrolujUdaje();
    }//GEN-LAST:event_jtf_doplnk_infoActionPerformed
    /**
     *prida noveho zakaznika do databazy
     *
     **/
    private void btn_pridaj_zakaznikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pridaj_zakaznikaActionPerformed
        Pouzivatel novy = new Pouzivatel(jtf_meno.getText(), jtf_priezvisko.getText(), jtf_adresa.getText(), jtf_cislo_OP.getText(), jtf_doplnk_info.getText(), jcb_pohlavie.getSelectedItem().toString(), jcb_stav.getSelectedItem().toString());
        
        //pridanie zakaznika do databazy
        Databaza db = new Databaza();
        db.pridajPouzivatela(novy);
        
        //zobrazenie informacii o zakaznikovy
        ZakaznikDetail zakaznikDetail = new ZakaznikDetail(novy);
        zakaznikDetail.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btn_pridaj_zakaznikaActionPerformed

    private void jtf_menoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_menoKeyTyped
        skontrolujUdaje();
    }//GEN-LAST:event_jtf_menoKeyTyped

    private void jtf_adresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_adresaKeyTyped
        skontrolujUdaje();
    }//GEN-LAST:event_jtf_adresaKeyTyped

    private void jtf_priezviskoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_priezviskoKeyTyped
        skontrolujUdaje();
    }//GEN-LAST:event_jtf_priezviskoKeyTyped

    private void jtf_cislo_OPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_cislo_OPKeyTyped
        skontrolujUdaje();
    }//GEN-LAST:event_jtf_cislo_OPKeyTyped

    
    private void skontrolujUdaje(){
        if (jtf_cislo_OP.getText().length() > 0 && jtf_meno.getText().length() > 0 && jtf_priezvisko.getText().length() > 0&& jtf_adresa.getText().length() > 0 && jtf_doplnk_info.getText().length() > 0) btn_pridaj_zakaznika.setEnabled(true);
        else btn_pridaj_zakaznika.setEnabled(false);
    }
    private void btn_zrus_zakaznikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zrus_zakaznikaActionPerformed
        
        jtf_adresa.setText("");
        jtf_meno.setText("");
        jtf_priezvisko.setText("");
        jtf_cislo_OP.setText("");
        
        this.dispose();
    }//GEN-LAST:event_btn_zrus_zakaznikaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovyPouzivatel().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Doplnk_info;
    private javax.swing.JButton btn_pridaj_zakaznika;
    private javax.swing.JButton btn_zrus_zakaznika;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox jcb_pohlavie;
    private javax.swing.JComboBox jcb_stav;
    private javax.swing.JTextField jtf_adresa;
    private javax.swing.JTextField jtf_cislo_OP;
    private javax.swing.JTextField jtf_doplnk_info;
    private javax.swing.JTextField jtf_meno;
    private javax.swing.JTextField jtf_priezvisko;
    // End of variables declaration//GEN-END:variables
    
}
