/*
 * ZakaznikDetail.java
 *
 * Created on 31 July 2008, 00:31
 */

package manola;

import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  simo
 */
public class ZakaznikDetail extends javax.swing.JFrame {
    
    public Pouzivatel pouzivatel;
    
    /** Creates new form ZakaznikDetail */
    public ZakaznikDetail() {
        initComponents();
    }
    
    /** Creates new form ZakaznikDetail */
    public ZakaznikDetail(Pouzivatel novy_pouzivatel) {
        initComponents();
        
        pouzivatel = novy_pouzivatel;
        
        jtf_meno.setText(pouzivatel.meno);
        jtf_priezvisko.setText(pouzivatel.priezvisko);
        jtf_adresa.setText(pouzivatel.adresa);
        jtf_cislo_OP.setText(pouzivatel.cislo_OP);
        jtf_doplnk_info.setText(pouzivatel.doplnk_info);
        
        
        jcb_pohlavie.setSelectedItem((Object)pouzivatel.pohlavie);
        jcb_stav.setSelectedItem((Object)pouzivatel.stav);
        
        zovrazZakaznikoveZmluvy(pouzivatel.cislo_OP);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtf_meno = new javax.swing.JTextField();
        jtf_priezvisko = new javax.swing.JTextField();
        jtf_adresa = new javax.swing.JTextField();
        jtf_cislo_OP = new javax.swing.JTextField();
        jcb_pohlavie = new javax.swing.JComboBox();
        jcb_stav = new javax.swing.JComboBox();
        btn_zavri = new javax.swing.JButton();
        btn_pridaj_zmluvu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_zmluvy_zakaznnika = new javax.swing.JTable();
        Dopnk_info = new javax.swing.JLabel();
        jtf_doplnk_info = new javax.swing.JTextField();
        btn_zmluva_detail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail Zakaznika");
        jLabel1.setText("Meno");

        jLabel2.setText("Priezvisko");

        jLabel3.setText("Adresa");

        jLabel4.setText("Rodne Cislo");

        jLabel5.setText("Pohlavie");

        jLabel6.setText("Stav");

        jtf_meno.setEditable(false);

        jtf_priezvisko.setEditable(false);

        jtf_adresa.setEditable(false);

        jtf_cislo_OP.setEditable(false);

        jcb_pohlavie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muz", "Zena" }));
        jcb_pohlavie.setEnabled(false);

        jcb_stav.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Slobodny/a", "Zenaty/Vydata" }));
        jcb_stav.setEnabled(false);

        btn_zavri.setText("Zavri okno");
        btn_zavri.setToolTipText("Zavrie toto okno");
        btn_zavri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zavriActionPerformed(evt);
            }
        });

        btn_pridaj_zmluvu.setText("Pridaj zmluvu");
        btn_pridaj_zmluvu.setToolTipText("Vytvory a prida novu zmluvu zakaznikovi\n");
        btn_pridaj_zmluvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pridaj_zmluvuActionPerformed(evt);
            }
        });

        tbl_zmluvy_zakaznnika.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        tbl_zmluvy_zakaznnika.setToolTipText("Zmluvy uzavrete so zakaznikom");
        jScrollPane1.setViewportView(tbl_zmluvy_zakaznnika);

        Dopnk_info.setText("Cislo OP");

        jtf_doplnk_info.setEditable(false);

        btn_zmluva_detail.setText("Detail zmluvy");
        btn_zmluva_detail.setToolTipText("Zobrazi detail vybranej zmluvy.");
        btn_zmluva_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_zmluva_detailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(Dopnk_info)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_doplnk_info)
                                    .addComponent(jtf_cislo_OP)
                                    .addComponent(jtf_priezvisko, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtf_meno, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                    .addComponent(jtf_adresa))
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jcb_pohlavie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(177, 177, 177))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jcb_stav, 0, 235, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGap(120, 120, 120)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_zavri, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(btn_pridaj_zmluvu, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(btn_zmluva_detail, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtf_meno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtf_priezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtf_adresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtf_cislo_OP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_pridaj_zmluvu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_zavri)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dopnk_info)
                            .addComponent(jtf_doplnk_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jcb_pohlavie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcb_stav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btn_zmluva_detail)))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
        );
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-616)/2, (screenSize.height-418)/2, 616, 418);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_zmluva_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zmluva_detailActionPerformed
        //ak nieje nic vybrane
        if(tbl_zmluvy_zakaznnika.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Vyber zaznam v tabulke zmluv pouzivatela", "Chyba",0);
        }
        else{
            ZmluvaDetail zmluvaDetail = new ZmluvaDetail(tbl_zmluvy_zakaznnika.getValueAt(tbl_zmluvy_zakaznnika.getSelectedRow(),0).toString());
            zmluvaDetail.setVisible(true);
        }
    }//GEN-LAST:event_btn_zmluva_detailActionPerformed

    private void btn_pridaj_zmluvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pridaj_zmluvuActionPerformed
        NovaZmluva novaZmluva = new NovaZmluva(pouzivatel);
        novaZmluva.setVisible(true);
    }//GEN-LAST:event_btn_pridaj_zmluvuActionPerformed

    private void btn_zavriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_zavriActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_zavriActionPerformed
    
    private void zovrazZakaznikoveZmluvy(String cislo_OP){
       DefaultTableModel mdl = new DefaultTableModel();
       
       tbl_zmluvy_zakaznnika.setModel(mdl);
       
       while(tbl_zmluvy_zakaznnika.getRowCount() > 0){
            mdl.removeRow(0);
       }
       
       mdl.addColumn("ID");
       mdl.addColumn("Zakaznik");
       mdl.addColumn("Predmet");
       mdl.addColumn("Suma");
       mdl.addColumn("Stav");
       mdl.addColumn("Poznamka");
       
       Databaza db = new Databaza();
       
       Object[] zmluvy = db.vratZmluvy(cislo_OP);
           
       for (int i = 0; i < zmluvy.length; i++) {
           Zmluva nova = (Zmluva)zmluvy[i];
           if(nova.datum.getYear() == 2008){
               mdl.addRow(new Object[] {nova.ID.toString(), nova.zakaznik_OP.toString(), nova.predmet.toString(), nova.hodnota+" SK", nova.stav.toString(), nova.poznamka.toString()});
           }
           else{
               mdl.addRow(new Object[] {nova.ID.toString(), nova.zakaznik_OP.toString(), nova.predmet.toString(), nova.hodnota+" € ", nova.stav.toString(), nova.poznamka.toString()});
           }
           
       }
    }   

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZakaznikDetail().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dopnk_info;
    private javax.swing.JButton btn_pridaj_zmluvu;
    private javax.swing.JButton btn_zavri;
    private javax.swing.JButton btn_zmluva_detail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcb_pohlavie;
    private javax.swing.JComboBox jcb_stav;
    private javax.swing.JTextField jtf_adresa;
    private javax.swing.JTextField jtf_cislo_OP;
    private javax.swing.JTextField jtf_doplnk_info;
    private javax.swing.JTextField jtf_meno;
    private javax.swing.JTextField jtf_priezvisko;
    private javax.swing.JTable tbl_zmluvy_zakaznnika;
    // End of variables declaration//GEN-END:variables
    
}
