name: Build JAR (Ant)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      # v4 works; just make sure submodules aren't needed
        uses: actions/checkout@v4

      - name: Set up JDK 11 (safer for db4o)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Install Ant and show versions
        run: |
          sudo apt-get update
          sudo apt-get install -y ant
          java -version
          ant -version

      - name: List Ant targets
        run: |
          ant -p || true

      - name: Build (force clean + jar, verbose, UTF-8)
        run: |
          set -e
          ant -noinput -Dfile.encoding=UTF-8 -v clean jar | tee build.log
          echo "---- If a jar was written, you'll see 'destfile=' lines above ----"
          grep -i "destfile=.*\.jar" -n build.log || true

      - name: Upload build log (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      - name: List any JARs found
        if: always()
        run: |
          echo "Searching for JARs..."
          find . -type f -name "*.jar" -print | sort || true

      - name: Upload app JAR (expected path)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: dist/manola.jar
          if-no-files-found: warn

      - name: Upload all jars (fallback)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: all-jars
          path: |
            **/*.jar
