<?xml version="1.0" encoding="UTF-8"?>
<project name="ManolaApp" default="jar" basedir=".">

  <!-- Folders -->
  <property name="src.dir"   value="src"/>
  <property name="build.dir" value="build/classes"/>
  <property name="dist.dir"  value="dist"/>
  <property name="lib.dir"   value="lib"/>

  <!-- Classpath: include all JARs under lib/ -->
  <path id="project.classpath">
    <fileset dir="${lib.dir}">
      <include name="**/*.jar"/>
    </fileset>
  </path>

  <!-- Clean -->
  <target name="clean">
    <delete dir="${build.dir}"/>
    <delete dir="${dist.dir}"/>
  </target>

  <!-- Compile with UTF-8 -->
  <target name="compile">
    <mkdir dir="${build.dir}"/>
    <javac srcdir="${src.dir}" destdir="${build.dir}"
           includeantruntime="false" debug="true"
           source="1.8" target="1.8" encoding="UTF-8">
      <classpath refid="project.classpath"/>
      <!-- If you need Java 11/17, change source/target to 11 or 17 -->
    </javac>
  </target>

  <!-- Package JAR with manifest -->
  <target name="jar" depends="compile">
    <mkdir dir="${dist.dir}"/>
    <jar destfile="${dist.dir}/ManolaApp.jar" basedir="${build.dir}">
      <manifest>
        <!-- Put your main class here (package.ClassName) -->
        <attribute name="Main-Class" value="manola.Tlac"/>
        <!-- Runtime classpath: list jars in lib/ (space-separated).
             If none needed, you can keep just 'lib/' so relative path works. -->
        <attribute name="Class-Path" value="lib/"/>
      </manifest>
    </jar>
  </target>

</project>
