name: Build JAR (Ant, debug)

on:
  push: { branches: [ main ] }
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # Try several JDKs because older NetBeans/Ant projects often expect 8 or 11
      matrix:
        java: [ '8', '11', '17', '21' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tree
        run: |
          echo "== Workspace files =="
          ls -la
          echo "== build.xml preview =="
          sed -n '1,120p' build.xml || true

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Install Ant
        run: |
          sudo apt-get update
          sudo apt-get install -y ant

      - name: Ant diagnostics
        run: |
          ant -diagnostics || true

      - name: Build with Ant (verbose, UTF-8)
        env:
          # Help with Slovak diacritics & resource encoding
          JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
          ANT_OPTS: -Dfile.encoding=UTF-8
        run: |
          # Common NetBeans targets are "clean" and "jar" or "dist".
          # We run "clean" first, then try "jar", and if missing, try "dist".
          set -euxo pipefail
          if ant -noinput -v -Dfile.encoding=UTF-8 clean jar; then
            echo "Built using 'jar' target."
          else
            echo "Target 'jar' not found or failed; trying 'dist'…"
            ant -noinput -v -Dfile.encoding=UTF-8 clean dist
          fi

      - name: List outputs
        run: |
          echo "== dist directory =="
          ls -la dist || true
          echo "== build directory =="
          ls -la build || true

      - name: Upload artifacts (JAR and logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jar-${{ matrix.java }}
          path: |
            dist/*.jar
            dist/lib/**
            **/build.log
          if-no-files-found: warn
