      - name: Upload build log (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      - name: List any JARs that were built
        if: success()
        run: |
          echo "Searching for JARs..."
          find . -type f -name "*.jar" -not -path "./lib/*" -print | sort || true

      - name: Upload JARs (common locations)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: |
            dist/**/*.jar
            build/**/*.jar
            target/**/*.jar
            **/build/libs/**/*.jar
