name: Build JAR (Ant)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'   # change to '11' or '21' if needed

      - name: Install Ant and show versions
        run: |
          sudo apt-get update
          sudo apt-get install -y ant
          java -version
          ant -version

      - name: Show project structure
        run: |
          pwd
          ls -la
          echo "---- Ant targets ----"
          ant -p || true

      - name: Build with Ant (verbose, UTF-8)
        run: |
          set -e
          ant -noinput -Dfile.encoding=UTF-8 -v clean jar | tee build.log

      - name: Upload build log (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      - name: Upload JAR artifact (if success)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: dist/*.jar
